apiVersion: v1
kind: ConfigMap
metadata:
  name: test-config
data:
  message: {{ .Values.config.message }}
  enabled: {{ .Values.config.enabled }}
  non-string-key: {{ get .Values.integerKey "1234" }}
  non-string-key-alternate: {{ index .Values.integerKey "1234" }}
